//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyPlannerWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCustomer
    {
        public int CustID { get; set; }

        [DisplayName("First Name")]
        [Required]
        public string CustFName { get; set; }

        [DisplayName("Last Name")]
        [Required]
        public string CustLName { get; set; }

        [DisplayName("House Name/Number")]
        [Required]
        public string CustHouseAddress { get; set; }

        [DisplayName("Street")]
        [Required]
        public string CustStreet { get; set; }

        [DisplayName("Town")]
        [Required]
        public string CustTown { get; set; }

        [DisplayName("Dublin Number")]
        [Required]
        public int CustCity { get; set; }

        [DisplayName("Email")]
        [Required]
        public string CustEmail { get; set; }

        [DisplayName("Phone Number")]
        public Nullable<int> CustPhone { get; set; }

        [DisplayName("Party Size")]
        public Nullable<int> CustCapacity { get; set; }

        [DisplayName("Password")]
        [Required]
        public string CustPassword { get; set; }
    }

}
