CREATE TABLE [dbo].[Entertainers] (
    [id]               INT            IDENTITY (1, 1) NOT NULL,
    [Username]         NVARCHAR (MAX) NULL,
    [Email]            NVARCHAR (MAX) NULL,
    [Password]         NVARCHAR (MAX) NULL,
    [FirstName]        NVARCHAR (MAX) NULL,
    [LastName]         NVARCHAR (MAX) NULL,
    [Street]           NVARCHAR (MAX) NULL,
    [Town]             NVARCHAR (MAX) NULL,
    [City]             NVARCHAR (MAX) NULL,
    [PhoneNumber]      INT            NOT NULL,
    [IsMagician]       BIT            NOT NULL,
    [IsClown]          BIT            NOT NULL,
    [IsBalloonAnimals] BIT            NOT NULL,
    [IsPettingZoo]     BIT            NOT NULL,
    [IsCakes]          BIT            NOT NULL,
    [IsCatering]       BIT            NOT NULL,
    [IsFacePainting]   BIT            NOT NULL,
    [IsJuggling]       BIT            NOT NULL,
    [IsDJ]             BIT            NOT NULL,
    [IsPartyGames]     BIT            NOT NULL,
    [IsBouncyCastle]   BIT            NOT NULL,
    [IsPuppets]        BIT            NOT NULL,
    [IsHennaTattoos]   BIT            NOT NULL,
    [IsHairBraiding]   BIT            NOT NULL,
    [IsOther]          BIT            NOT NULL,
    [CustomerId] INT NOT NULL, 
    CONSTRAINT [PK_dbo.Entertainers] PRIMARY KEY CLUSTERED ([id] ASC)
);

